apiVersion: apps/v1
kind: Deployment
metadata:
  name: memweb-reconciler
spec:
  replicas: 1
  selector:
    matchLabels:
      name: memweb-reconciler
  template:
    metadata:
      labels:
        name: memweb-reconciler
        app: memweb-reconciler
    spec:
     #serviceAccountName: memweb-reconciler
      containers:
        - name: memweb-reconciler
          # Replace this with the built image name
          image: docker.io/mhrivnak/memweb-reconciler
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "memweb-reconciler"

---
apiVersion: v1
kind: Service
metadata:
  name: memweb-reconciler
spec:
  selector:
    app: memweb-reconciler
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
