apiVersion: apps/v1
kind: Deployment
metadata:
  name: memweb-reconciler
spec:
  replicas: 1
  selector:
    matchLabels:
      name: memweb-reconciler
  template:
    metadata:
      labels:
        name: memweb-reconciler
    spec:
      serviceAccountName: memweb-reconciler
      containers:
        - name: memweb-reconciler
          # Replace this with the built image name
          image: REPLACE_IMAGE
          command:
          - memweb-reconciler
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "memweb-reconciler"
